### ISSUE TITLE
MagickCore::Image {aka struct MagickCore::_Image}' has no member named 'intensity'

### ISSUE THREAD

**Issue by zengxianyu** [jgain/EcoLearn#1]
Thanks for the great work. I encountered an error while building the project. In line 37 of common/map_rgba.cpp it says that MagickCore::Image {aka struct MagickCore::_Image}' has no member named 'intensity'. 

I checked the provided ImageMagick-6.8.1-10 and found there's no member intensity in _Image as told

**Comment by zengxianyu** [comment]
I found the _Image in ImageMagick-6.9 has the member intensity. So the correct version is 6.9?

**Comment by k-kapp** [comment]
Hi @zengxianyu, thank you for the positive feedback. Yes, on my Ubuntu PC on which I can build and run it, my ImageMagick version is actually 6.9.9-7. The 6.8 we specified was, I suspect, from a readme from earlier on in the project which we just copy-pasted into the final readme without checking it again. Thanks for spotting it and I will update the final readme to reflect this. 

On the website where we specify the `wget` address, 6.9.9-7 does not seem to be available, but the closest version seems to be 6.9.9-51. I probably downloaded my specific version via the Linux package manager (`apt`), although I will have to check again. I will try it out with the 6.9.9-51 version and if it works I will update the `wget` statement in  the EcoSynth/README.txt file.

**Comment by k-kapp** [comment]
Ok, can confirm that the interface works with ImageMagick version 6.9.9-51 on my system. Let me know if it works for you also and I will update the readme and close the issue @zengxianyu.

**Comment by k-kapp** [comment]
So, the updated install instructions for ImageMagick will be

```
wget https://www.imagemagick.org/download/releases/ImageMagick-6.9.9-51.tar.xz
tar -xf ImageMagick-6.9.9-51.tar.xz
cd ImageMagick-6.9.9-51
./configure
make
make install
```

The last command, `make install`, might give a permission error. In that case it should be `sudo make install`.

**Comment by zengxianyu** [comment]
Thank you for the detailed response. However I still cannot run the script, specifically the viewer for loading the scene file. It says ``GPUassert: unknown error /home/alex/Desktop/EcoLearn/data_importer/map_procs.cu 91." 
Could you provide an example input image (such as the commented out ''input.png'' in the pix2pix_server.py) to allow me to try the deep learning model alone?
